### PR TITLE
v1

### PR DESCRIPTION
**Pull request by philmander**
I've taken ownership of this package and made some updates:

* Code adapted from latest `mobx-react` to be Preact specific.
* Removed a few features to slim things down a bit and simplify the code. See README (although I'm open to putting these back)
* Continue to support @connect from mobx-preact 0.x
* I migrated the test suite to my preference, Jest, because I find it's built-in JSDom support makes it easy to work with Preact

Thanks @nightwolfz for transferring ownership

### CODE REVIEW

**Comment by mweststrate** [comment]
Great stuff @philmander !

**Comment by philmander** [comment]
Thanks @mweststrate , I only started out trying to add a few features to mobx-observer and ended up here!

**Comment by nightwolfz** [comment]
Amazing work @philmander  !

**Comment by philmander** [comment]
Thanks @nightwolfz , but it was mainly just find and replace "react" --> "preact" !!!

**Pull request merged**
